services:
  - type: web
    name: stakeclock-case-study
    env: static
    buildCommand: npm run build
    staticPublishPath: ./build
    domains:
      - stakeclock.xyz
      - www.stakeclock.xyz
    envVars:
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 